"""
Django settings for blog_proj project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from decouple import config

"""
This code is the Django settings module for the "blog_proj" project. Here's a breakdown of the code:

- `BASE_DIR`: Defines the base directory of the project using the `Path` object from the `pathlib` module.

- `SECRET_KEY`: Specifies the secret key used for cryptographic signing and securing various aspects of the Django project. It's important to keep this key secret in production.

- `DEBUG`: Determines whether the project is in debug mode. When set to `True`, it enables detailed error reporting. In production, it should be set to `False` for security reasons.

- `ALLOWED_HOSTS`: A list of host/domain names that the Django project is allowed to serve. It should be configured to include the appropriate domain names when deploying the project.

- `INSTALLED_APPS`: A list of installed applications for the Django project. It includes both Django's built-in apps (`django.contrib`) and custom apps (`blog_app` and `users`).

- `MIDDLEWARE`: A list of middleware classes used by the Django project. Middleware handles requests and responses globally during the request/response cycle.

- `ROOT_URLCONF`: Specifies the root URL configuration module for the Django project.

- `TEMPLATES`: A list of template engines and their configurations for rendering HTML templates.

- `WSGI_APPLICATION`: Specifies the WSGI application used for running the Django project.

- `DATABASES`: Configures the database settings for the project. In this case, it uses SQLite as the default database engine.

- `AUTH_PASSWORD_VALIDATORS`: A list of password validation validators for user passwords.

- `LANGUAGE_CODE`: The default language code for the project.

- `TIME_ZONE`: The time zone used in the project.

- `USE_L10N`: Specifies whether to use localization for formatting dates, numbers, and time.

- `USE_I18N`: Specifies whether to use internationalization for translating strings.

- `USE_TZ`: Specifies whether to use time zones in the project.

- `LANGUAGES`: A tuple of available languages for the project. Each language is defined with a language code and its display name.

- `LOCALE_PATHS`: A list of directories containing translation files for different languages.

- `STATIC_URL`: The URL prefix for serving static files.

- `MEDIA_URL`: The URL prefix for serving media files.

- `MEDIA_ROOT`: The directory where uploaded media files will be stored.

- `STATICFILES_DIRS`: A list of directories from which static files will be collected.

- `DEFAULT_AUTO_FIELD`: The default primary key field type for newly created models.

- `LOGIN_REDIRECT_URL`: The URL to redirect to after a successful login.

- `LOGOUT_REDIRECT_URL`: The URL to redirect to after a successful logout.

- `EMAIL_BACKEND` and related settings: Configuration for sending email using Gmail as the SMTP server.

Overall, this code configures various settings for the Django project, including database, internationalization, static files, media files, authentication, email, and more.
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bn2ivpuruy*3z+fc!h)an7+$mqfaj3kps!ti1es7&$)#uhse6z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'blog_app',
    'users',
    
    'ckeditor',
    'hitcount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Kiev'#'UTC'

USE_L10N = True

USE_I18N = True

USE_TZ = True

LANGUAGES = (
    ('en', _('English')),
    ('ru', _('Russian')),
)

LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'



# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
