# Generated by Django 4.1.7 on 2023-04-02 08:18

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.ImageField(blank=True, help_text='User photo', null=True, upload_to='images/profile/')),
                ('user_description', models.TextField(blank=True, help_text='User description', null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='Registration date')),
                ('user_link', models.CharField(blank=True, help_text='User link', max_length=200, null=True)),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(help_text='Post title', max_length=200)),
                ('post_image', models.ImageField(blank=True, help_text='Post image', null=True, upload_to='images/')),
                ('post_content', ckeditor.fields.RichTextField(blank=True, help_text='Post content', null=True)),
                ('post_category', models.CharField(default='programming', help_text='Post category', max_length=200)),
                ('post_date', models.DateTimeField(auto_now_add=True, help_text='Post date')),
                ('post_author', models.ForeignKey(help_text='Post author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
