# Generated by Django 4.1.7 on 2023-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_post_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_birth_date',
            field=models.DateField(blank=True, help_text='User birth date', null=True),
        ),
    ]
