# Generated by Django 4.1.7 on 2023-05-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_profile_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_github_url',
            field=models.CharField(blank=True, help_text='User GitHub url', max_length=200, null=True),
        ),
    ]
