# Generated by Django 4.1.7 on 2023-05-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_profile_user_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.TextField(blank=True, help_text='Phone', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_link',
            field=models.CharField(blank=True, help_text='User social network link', max_length=200, null=True),
        ),
    ]
