# Generated by Django 4.1.7 on 2023-06-02 10:45

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_alter_comment_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='svg_icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/', validators=[blog_app.models.validate_svg]),
        ),
    ]
