# Generated by Django 4.1.7 on 2023-06-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_remove_post_dislikes_remove_post_likes_post_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
