# Generated by Django 4.1.7 on 2023-06-21 08:13

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_alter_category_description_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, validators=[blog_app.models.validate_name_for_category]),
        ),
    ]
