# Generated by Django 4.1.7 on 2023-06-21 08:36

import blog_app.models
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=ckeditor.fields.RichTextField(default='Comment', validators=[blog_app.models.validate_comment_content_for_comment]),
        ),
    ]
