# Generated by Django 4.1.7 on 2023-06-21 08:42

import blog_app.models
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_alter_comment_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor.fields.RichTextField(default='Post content', validators=[blog_app.models.validate_post_content_for_post]),
        ),
    ]
