# Generated by Django 4.1.7 on 2023-06-21 08:57

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_alter_post_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[blog_app.models.validate_phone_for_profile]),
        ),
    ]
